<div class="ascii-container">
  <pre class="ascii">
               .''''''''.
              ;M0dxddxdOM;
              lM:      ,Ml
;xkkkkkkkkkkkkKMKkkkkkk0MKkkkkkkkkkkkkx;
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWKKKKKKWMMMMMMMMMMMMMMMM
kkkkkkkkkkkkkkkk, ';;' ,kkkkkkkkkkkkkkkk
cccccccccccccccc. KMMK .cccccccccccccccc
MMMMMMMMMMMMMMMM: ;::; :MMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNOOOOOONMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX
 ...'..'..'..'..'..''..'..'..'..'..'...
      </pre>
</div>
